-- AlterTable
ALTER TABLE "Story" ALTER COLUMN "endTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "activityEnded" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "activityStarted" SET DEFAULT CURRENT_TIMESTAMP;
